# By: mrlucasfreitas
# https://github.com/mrlucasfreitas

# Install public key in VM
# The public key must be located in ~/.ssh/id_rsa
ssh_pub_key = File.read("#{Dir.home}/.ssh/id_rsa.pub")

ssh_setup_script = <<-SCRIPT
  ssh_authorized_keys="/home/vagrant/.ssh/authorized_keys"
  echo '#{ssh_pub_key}' >> "$ssh_authorized_keys"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "vagrant-execute-script"
  config.vm.box = "bento/centos-7"
  config.vm.box_version = "202002.04.0"
  config.vm.hostname = "vagrant-execute-script.local"
  config.vm.network :private_network, ip: "172.16.14.11"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "vagrant-execute-script"
    vb.gui = false
    vb.cpus = 1
    vb.memory = 512
  end

  config.vm.provision "shell", inline: ssh_setup_script, privileged: false
end